function vars = readRamchandraData(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read
%  plotFlag: 1 if plot, 0 if no plots

%  Auto-generated by MATLAB on 25-Oct-2024 09:53:24

% Import the file
addpath 'C:\Users\mmgee\Box\Data-Acquisition\Neuro-Data-Acq\Auckland-physiology-data\upload-folder-for-Rohit-Ramchandra'
newData1 = load('-mat', fileToRead1);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('caller', vars{i}, newData1.(vars{i}));
end




